name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on:
    # 手動実行できる様にする
    workflow_dispatch:
        branches:
            - master
    # プッシュでワークフローを起動する
    # ただしmasterブランチに対してのみ
    push:
        branches:
            - master
    schedule:
        # * はYAMLに置ける特殊文字なので、この文字列は引用符で囲まなければならない
        - cron: "0 14 * * *"

jobs:
    build:
        # Job name is Greeting
        name: Greeting
        # This job runs on Linux
        runs-on: ubuntu-latest
        # env:
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - run: npm ci
            - run: npm run eslint
            - run: npm run prettier
            - run: npm run test
            - run: npm run webpack
            # - run: npm run kintone-customize-uploader -- --password ${{ secrets.USER_PASSWORD }} --username ${{ secrets.USER_NAME }} --domain tech-tech-kintone.cybozu.com
            - run: npx ginue pull -l dist/ginue -p ${{ secrets.USER_PASSWORD }} -u ${{ secrets.USER_NAME }}
            - uses: actions/upload-artifact@v2
              with:
                  name: webpack
                  path: dist/
