name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
    build:
        # Job name is Greeting
        name: Greeting
        # This job runs on Linux
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - run: npm ci
            - run: npm run eslint
            - run: npm run prettier
            - run: npm run test
            - run: npm run webpack
            - run: npm run kintone-customize-uploader -- --password ${{ secrets.USER_PASSWORD }} --username ${{ secrets.USER_NAME }} --domain tech-tech-kintone.cybozu.com
            - uses: actions/upload-artifact@v2
              with:
                  name: webpack
                  path: dist/
