name: Secret Playground
# This workflow is triggered on pushes to the repository.
on:
    push:
        # Sequence of patterns matched against refs/heads
        branches:
            # Push events on master branch
            - master
            - secret

jobs:
    build:
        name: log my secret
        # This job runs on Linux
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - run: echo ${{ secrets.MY_IMPORTANT_SECRET }}
